apiVersion: v1
kind: Service
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    app: {{ include "plex.name" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "plex.name" . }}
