name: ci/cd

on:
  push:
    branches:
      - "main"
      # - "development"
    paths:
      - "Docker/**" #Solo cambios en la carpeta Docker

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Docker/Dockerfile

  # trivy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Build an image from Dockerfile
  #       run: |
  #         docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
  #     - name: Run Trivy vulnerability scanner
  #       uses: aquasecurity/trivy-action@master
  #       with:
  #         image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
  #         format: 'table'
  #         exit-code: '1'
  #         ignore-unfixed: true
  #         vuln-type: 'os,library'
  #         severity: 'CRITICAL,HIGH'

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          # context: .
          file: Docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopsm16:latest
