name: ci/cd

on:
  push:
    branches:
      - "main"
      - "development"
    # paths:
    #   - "Docker/**" #Solo cambios en la carpeta Docker

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Docker/Dockerfile

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          # context: ./Docker/
          file: Docker/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopsm16:latest

      - name: Scan vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.docker_build.outputs.image }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopsm16:latest
